name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag abhishekcha/netflix-clone:latest
  
      - name: Docker Build & Push to Docker Hub
        uses: timzu/github-actions-docker@master
        with:
          args: --docker
        env:
          USERNAME: ${{ secrets.DOCKERHUB_LOGIN }}
          PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
          DOCKERFILE: "Dockerfile"
          IMAGE_NAME: "abhishekcha/netflix-clone"
          TAG_NAME: "v0.0.1"
          LATEST: "true"
