name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

    - name: DockerHub Build And Push
      uses: Abhishek-070/Dockerhub-Build-Push@v1.0
          with:
          registry_url: 'docker.io'
          repository_name: 'abhishekcha/netflix-clone'
          user_name: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          image_version: 'v1.0'
          docker_file: '.'
          
